/*
   Freitag, 4. Februar 2005 16:35:19
   Benutzer: 
   Server: (local)
   Datenbank: efSurveyManagerNET
   Anwendung: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.tdAnswerValues ADD
	val_default bit NULL
GO
COMMIT
